# prefix
unbind C-b
set -g prefix C-f
bind C-f send-prefix

# double prefix -> last window
bind-key C-f last-window

set -g mouse on
set -g history-limit 1000000

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g display-panes-time 3000
set -g display-time 3000

set -s escape-time 0

set -g default-terminal "tmux-256color"

# ghostty / modern terminal support
set -ga terminal-features ",xterm-256color:RGB"
set -ga terminal-features ",xterm-ghostty:RGB,focus,ccolour,cstyle"
set -ga terminal-features ",*:hyperlinks"

# wayland clipboard
set -s set-clipboard on

# better terminal interaction
set -g focus-events on

setw -g mode-keys vi
set -g status-keys emacs

# copy mode
bind-key Space copy-mode
bind-key / copy-mode \; send-key ?

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

# mouse copy
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel

# shell history navigation
bind-key -T edit-mode-vi Up send-keys -X history-up
bind-key -T edit-mode-vi Down send-keys -X history-down

# open in current working directory
bind-key v split-window -h -c "#{pane_current_path}"
bind-key s split-window -v -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"

# pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# resize panes
bind-key H resize-pane -L 10
bind-key J resize-pane -D 10
bind-key K resize-pane -U 10
bind-key L resize-pane -R 10

# layouts
bind-key = select-layout even-horizontal
bind-key | select-layout even-vertical

# move windows
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

# kill pane instantly
bind-key x kill-pane

bind C-s if -F '#{pane_synchronized}' \
  'setw synchronize-panes off; display-message "sync off"' \
  'setw synchronize-panes on; display-message "sync on"'

set -g pane-border-lines single

set -g pane-border-status bottom
set -g pane-border-format " #P #{pane_current_command} "

set -g pane-active-border-style fg=green

set -g set-titles on
set -g set-titles-string "#T"

# auto rename windows
set-option -g automatic-rename on

unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux reloaded"

set -g @plugin 'tmux-plugins/tpm'

# resurrect + continuum
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# auto restore tmux environment
set -g @continuum-restore 'on'

# save pane contents too
set -g @resurrect-capture-pane-contents 'on'

# vim + tmux seamless navigation
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'
